name:                ray-tracer-challenge
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/ray-tracer-challenge#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2022 Author name here
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - vector
  - text
  - QuickCheck
  - checkers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - RayTracer.Color
    - RayTracer.Canvas
    - RayTracer.Tuple
    - RayTracer.Matrix
    - RayTracer.Heap
    - RayTracer.Ray
    - RayTracer.Light
    - Example.Projectile
    - Example.Clock
    - Example.SimpleSphere
    - Example.ShadedSphere

executables:
  ray-tracer-challenge:
    main:             Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ray-tracer-challenge

tests:
  ray-tracer-challenge-test:
    main:                Spec.hs
    other-modules:
      - SpecHelper
      - Approximate
    source-dirs:         test
    default-extensions:
      - ScopedTypeVariables
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-type-defaults
    - -fno-warn-missing-home-modules
    dependencies:
    - ray-tracer-challenge
    - hspec
    - hspec-discover
    - checkers
    - QuickCheck
    - hedgehog
